language: ruby
cache: bundler
script:
- bundle exec rake spec
rvm:
- 2.4.5
- 2.5.7
matrix:
  fast_finish: true
deploy:
  provider: rubygems
  on:
    rvm: 2.5.7
    tags: true
    all_branches: true
  api_key:
    secure: "jO6NhdgFkYPaqpAPcAKRFqrEsEyRDPnn5npBw6SO+PdbYM0j/ljjcMFJ/KIelVxp5OuX7OO03AIo40EgXvuAVZr5KdrQLt0GOEcmjaz7yUqhZZugmlwT6z1W6f5L6Ielb5YCQP6oAwH9PVftILJWdizDCLI+P8+g/MFiPmCHdVz25H0qWZm6ssooHAd9opeEExyuFWKueHhyZafCm8L8hwzpvA72AsSyF15Wzu/JWhnUhcAQAAW3+rg7Y9ZOaD6YDOpDFfZyM0HCqYxsy/hP77o0iRFkNxRh1TYrmNbdE1aJ02XBPw6p80nUhYRr0aLa23OVAGhDVhurcSSF/+tRuaU1DagLEVYCzMRajVK/F7+awZQ9la/Rv6bAkWIfkFpTTV8lLkCvt4tlUhkTMmTF0Qhhk5r8JnVuwCGZC+T8mv124KYpn4MprLbBjbiBTY1ttoT8nPuBbkcPZYZsmQQST12NPAADZlcCnthk7Ze0LA+XUIRcCzn4G5HPA5dZa4mp68rU1fEt2a9odT2/bzCyjPJlHDcdDBqh5q8xL+XwN3FhgUXgmqHiFzFwEk1ygB0hsUHOBPz7kAVX1WTXSqIs1XdHxiLZvnP5ocsD2Zs1ScAQ+0Qd+Hrv4x/Zl9Vz1V7a26W58HFN9lGgY/h7R0Kzd6PRvNFsqce6xaIhKg7lUrM="
notifications:
  email: false
